### ISSUE TITLE
Zusätzlicher Hinweis in Doku

### ISSUE THREAD

**Issue by oweitman** [buanet/docs#11]
Im Abschnitt
https://docs.buanet.de/de/iobroker-docker-image/docs/#aktualisierung-update

hast du folgendes geschrieben

**_Die im ioBroker Docker Image enthaltenen Linux Pakete lassen sich manuell über den integrierten Paketmanager apt aktualisieren. Dabei unterscheidet sich die Vorgehensweise nicht von der anderer auf Debian basierender Linux Systeme und erfolgt über die Kommandozeile des Containers._**

**_Beachte, dass der empfohlene Weg allerdings das Herunterladen des aktuellen ioBroker Docker Images und anschließende Neuerstellen des Containers ist._**

Ich würde den letzten Absatz noch mit folgendem Erweitern:

**_Beachte, dass der empfohlene Weg allerdings das Herunterladen des aktuellen ioBroker Docker Images und anschließende Neuerstellen des Containers ist, da alle Änderungen des Images nach dem Neuerzeugen des Images verloren sind._**

Daher ist es eigentlich immer Unsinn am Containerbetriebssystem irgendwas zu ändern, was über den Status temporär hinausgeht. Das betrifft auch den Befehl iob nodejs-update
Nach dem nächsten recreate ist das alles wieder auf dem Stand der ursprünglichen Container-Definition.

**Comment by buanet** [comment]
Danke für den Hinweis.
